### ISSUE TITLE
Question about average hr array

### ISSUE THREAD

**Issue by jhoballah** [ss842/CloudECG_jsy#1]
For the average heart rate values, do you want them to be calculated by section, or should they be calculated as a sliding window?

In essence, if the acquisition goes for 60 seconds, and you set an averaging time period of 10 seconds, would you want 6 average times or to calculate an average HR value for each index as we go through the 10 second window?

Thanks!

**Comment by mlp6** [comment]
Player's choice...

**Comment by jhoballah** [comment]
Ok, sounds good! Also, the averaging time is now going to be in seconds instead of minutes, right?

**Comment by mlp6** [comment]
You can still do an average HR with BPM units... though the accuracy of such an average over a small window does come into question.
