### ISSUE TITLE
Sub-module Issues w/ updating

### ISSUE THREAD

**Issue by jhoballah** [ss842/CloudECG_jsy#10]
We're having an issue where our sub-module isn't updating in our repos (Sonali's and mine). I've tried re-cloning the Cloud repo and using --recursive to fetch and clone the repo, as well as getting the submodule separately using git submodule init and then git submodule update.

Any ideas why it seems to update for Yasha and not ours?

**Comment by jhoballah** [comment]
Bump <3

**Comment by jhoballah** [comment]
Also, if we were to make changes to the sub-module, should it be that they are created in the sub-module and then pushed back to the original repo, or should the original repo be where changes are made (and then pushed back to our sub-module)?

**Comment by suyashkumar** [comment]
Discussed and solved in office hours! Between 984653e62c51dbb5a32d1eb5f44eec85c525cd24 and 984653e62c51dbb5a32d1eb5f44eec85c525cd24 something changed that removed the .gitmodules file

**Comment by jhoballah** [comment]
Thanks again!
