### ISSUE TITLE
Update ReadMe

### ISSUE THREAD

**Issue by ss842** [ss842/CloudECG_jsy#7]
![image](https://user-images.githubusercontent.com/31519918/32280002-c88f0280-bef0-11e7-87c4-52cf4ef6474c.png)

**Comment by ss842** [comment]
![image](https://user-images.githubusercontent.com/31519918/32279993-c17315a4-bef0-11e7-9e98-682d68e58bc0.png)

**Comment by yashasaxena** [comment]
Did it in branch outside of master, will push accordingly
