### ISSUE TITLE
Sphinx Documentation 

### ISSUE THREAD

**Issue by ss842** [ss842/CloudECG_jsy#8]

**Comment by ss842** [comment]
![image](https://user-images.githubusercontent.com/31519918/32299441-fb4aa860-bf2b-11e7-9fff-69b8c51ce344.png)
![image](https://user-images.githubusercontent.com/31519918/32299465-1258caa0-bf2c-11e7-8051-33201dd0fead.png)

@mlp6 / @suyashkumar / @ad12  
any thoughts as to why make.bat html is not recognized as a command to create docs/_build/html ?

**Comment by mlp6** [comment]
`make.bat` will work from a Windows command prompt, but it looks like you are running `git bash`, which will not be able to interpret it.

**Comment by ss842** [comment]
this is how i was making the webpage in the last repo and had no issues with it. i thought that "cmd" going into the command line takes care of working in git bash not being able to interpret it

**Comment by mlp6** [comment]
You screen shots above made it look like those commands were being executed from `git bash`; did you ultimately get this to work?

**Comment by ss842** [comment]
the cmd command allows me get into my command line to use the make.bat command (this is how i was doing it in the last assignment)... wasn't working that day but the same thing worked the next day
