### ISSUE TITLE
Confusion on Getting data from server

### ISSUE THREAD

**Issue by yashasaxena** [ss842/CloudECG_jsy#9]
Hi,

We are just going through elements of our code related to posting and getting data from the server.

We successfully post proxy "time" and "voltage" dictionaries. However, I'm not able to properly test how to GET this data back to the client. I know you went over this in lecture.

Would you mind sending us an overview of how we would do this through our Flask App, and more immediately through our terminal. 

I'm attaching a screen shot of the test get function that I wrote. I only ran this after successfully posting data (note: this was through a different FLASK APP). Also, posting the latest error from Postman. 

<img width="432" alt="screen shot 2017-11-01 at 12 22 37 pm" src="https://user-images.githubusercontent.com/8584289/32285033-7eb3cf1a-beff-11e7-990a-05bdec66132c.png">
<img width="753" alt="screen shot 2017-11-01 at 12 22 22 pm" src="https://user-images.githubusercontent.com/8584289/32285037-8141a0c2-beff-11e7-964b-5429ccfce2e1.png">

Thanks!

**Comment by mlp6** [comment]
Is there any error thrown in the server terminal running your Flask app?

**Comment by yashasaxena** [comment]
yeah we are (see below, and also showing you what py file  i used):
<img width="817" alt="screen shot 2017-11-01 at 1 53 50 pm" src="https://user-images.githubusercontent.com/8584289/32289085-32fdff02-bf0c-11e7-975c-d15b1cde9366.png">
<img width="404" alt="screen shot 2017-11-01 at 1 54 00 pm" src="https://user-images.githubusercontent.com/8584289/32289094-3657415e-bf0c-11e7-8839-1a5a0cd10952.png">

**Comment by yashasaxena** [comment]
lol i just don't think we GET how to do it

**Comment by mlp6** [comment]
You are changing your code on me!!  :)  Can you point me to the specific line numbers in the code that you are referring to?  (You can get a permalink for those lines in GitHub and paste the URL here.)

**Comment by mlp6** [comment]
Regardless, in your latest code snippet above, I'm a bit confused.  You have a post method for `/api/heart_rate_summary`, but it doesn't actually accept anything; it simply returns a JSON string of your two dictionaries, correct?  If so, then it really only functions on a `GET` operation since it will only return something and not take in any data.  But then you have a `GET` method in `trial_get()`, but you appear to be using `request.args.get('time')` as something you would want to execute from your client, not a method on the server side.  Am I misinterpreting this?

**Comment by yashasaxena** [comment]
Thanks for looking at this! Yeah, so the main objective of all this was to test that:

1) If we send data to the server (/api/heart_rate/summary) through the post method(....this was done as a means to recreate what will be happening when you run our code) THEN 
2) Can we receive the data from the server through our flask app? 

We are super lost on how to execute #2. How should we retrieve the data you send to the server from the flask app? What would the syntax be and do we reference the same end point /api/heart_rate/summary?

**Comment by yashasaxena** [comment]
I thnk we got it now, fingers crossed
